### ISSUE TITLE
Create "question mark" pop-up when hovering status

### ISSUE THREAD

**Issue by allenxluo** [ctc-uci/the-literacy-project-frontend#37]
https://gyazo.com/5886fbf75448a246d6b87df5d2ac25f4

https://docs.google.com/document/d/1Tr-jaxFsyoYmlE4k9XcZ_91KkAmoQFJAlkyhbEELNfE/edit

Check prototype for flow.

**Comment by RileyChampion** [comment]
@allenxluo @anikait-rao This was already implemented in the 16-school-management in [src/components/Popover/InformationPopover.jsx](https://github.com/ctc-uci/the-literacy-project-frontend/commit/4492d80f2957d4a31b4259c00e74d0550e2945fc#diff-64d0e1b85fa9952840c1a59bfde7fe352111e7067aebd04769e29e4f8dedecd4)
