### ISSUE TITLE
Fix Button Text Coloring

### ISSUE THREAD

**Issue by ChaseC99** [ctc-uci/the-literacy-project-frontend#97]
Figma Style Guides show that all buttons (except for ones with Yellow Backgrounds), should have white text. 

![image](https://user-images.githubusercontent.com/29494270/161687125-5d01f4b1-9a50-4839-bd64-50cefb3c5464.png)
_Source: https://www.figma.com/file/eDLpjDWhK3IcsMmCvQgz5W/Style-Guide?node-id=0%3A1_

Currently the text is black on all of our button components.
<img width="671" alt="image" src="https://user-images.githubusercontent.com/29494270/161687216-7f947552-57ee-4945-85c4-0304b020ba63.png">

**Comment by anikait-rao** [comment]
closing, seems like this got fixed at some point
